using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

#region Required Global NameSpaces

using DataAccessLayer;
using EntityLayer;
using SecurityLayer;
using JobyCoWebCustomize.Models;
using System.Data;
using System.Web.Services;

using System.Net;
using System.Net.Mail;
using System.Configuration;
using System.Security.Cryptography;
using System.Globalization;

#endregion

namespace JobyCoWebCustomize
{
    public partial class LoggedContactUs : System.Web.UI.Page
    {
        #region Required Global Classes

        static clsOperation objOP = new clsOperation();
        static clsDB objDB = new clsDB();
        static clsCryptography objCG = new clsCryptography();
        static ControlModels objCM = new ControlModels();

        #endregion

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                #region Checking SessionID

                BOLogin ObjLogin = new BOLogin();
                ObjLogin = (BOLogin)Session["Login"];

                if (ObjLogin == null)
                {
                    Response.Redirect("/Login.aspx");
                }
                else
                {
                    string sessionid = ObjLogin.SESSIONID;
                    if (sessionid == "")
                    {
                        Response.Redirect("/Login.aspx");
                    }
                    else
                    {
                        Master.LoggedInUser = objOP.GetUserName(ObjLogin.EMAILID.ToString());
                    }
                }

                #endregion
            }
        }

        [WebMethod]
        public static string GetLatestContactId()
        {
            return objOP.GetAutoGeneratedValue("ContactId", "ContactUs", "CONT", 9);
        }

        [WebMethod]
        public static void AddContactDetails
            (
                string ContactId,
                string ContactTitle,
                string ContactFirstName,
                string ContactLastName,
                string ContactEmail,
                string ContactComments
            )
        {
            EntityLayer.ContactUs objCU = new EntityLayer.ContactUs();
            objCU.ContactId = ContactId;
            objCU.ContactTitle = ContactTitle;
            objCU.ContactFirstName = ContactFirstName;
            objCU.ContactLastName = ContactLastName;
            objCU.ContactEmail = ContactEmail;
            objCU.ContactComments = ContactComments;

            objDB.AddContactDetails(objCU);
            
        }
    }
}