using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

#region Required Global NameSpaces

using DataAccessLayer;
using EntityLayer;
using SecurityLayer;
using JobyCoWebCustomize.Models;
using System.Data;
using System.Web.Services;

using System.Net;
using System.Net.Mail;
using System.Configuration;

#endregion

namespace JobyCoWebCustomize
{
    public partial class Signup : System.Web.UI.Page
    {
        #region Required Global Classes

        static clsOperation objOP = new clsOperation();
        static clsDB objDB = new clsDB();
        static clsCryptography objCG = new clsCryptography();
        static ControlModels objCM = new ControlModels();

        #endregion

        protected void Page_Load(object sender, EventArgs e)
        {
            //hfUserId.Value = objOP.GetAutoGeneratedValue("UserId", "Users", "USR", 9);
        }

        [WebMethod]
        public static string GetUserId()
        {
            string sUserID = objOP.GetAutoGeneratedValue("UserId", "Users", "USR", 9);
            return sUserID;
        }

        [WebMethod]
        public static bool CheckUserId(string EmailID)
        {
            bool bExists = false;

            if (objOP.CheckExistence("EmailID", EmailID, "Users"))
                bExists = true;
            else
                bExists = false;

            return bExists;
        }

        [WebMethod]
        public static void AddUserDetails
            (
            string UserId,
            string EmailID,
            string Password,
            string Title,
            string FirstName,
            string LastName,
            string DOB,
            string Address,
            string Town,
            string Country,
            string PostCode,
            string Mobile,
            string Telephone,
            string SecretQuestion,
            string SecretAnswer,
            string UserRole,
            string Locked
            )
        {
            EntityLayer.User objUser = new EntityLayer.User();

            objUser.UserId = UserId;
            objUser.EmailID = EmailID;
            objUser.Password = objCG.getMd5Hash(Password);
            objUser.Title = Title;
            objUser.FirstName = FirstName;
            objUser.LastName = LastName;

            objUser.DOB = Convert.ToDateTime(DOB,
            System.Globalization.CultureInfo.GetCultureInfo("hi-IN").DateTimeFormat);

            objUser.Address = Address;
            objUser.Town = Town;
            objUser.Country = Country;
            objUser.PostCode = PostCode;
            objUser.Mobile = Mobile;
            objUser.Telephone = Telephone;
            objUser.SecretQuestion = SecretQuestion;
            objUser.SecretAnswer = SecretAnswer;
            objUser.UserRole = UserRole;
            objUser.Locked = Convert.ToBoolean(Locked);

            objDB.AddUserDetails(objUser);
        }

        [WebMethod]
        public static string SendSignupEmail(string EmailID, string Password)
        {
            string sMessage = string.Empty;
            string DomainName = HttpContext.Current.Request.Url.Scheme;
            DomainName += "://";
            DomainName += HttpContext.Current.Request.Url.Authority;
            //string sFrom = "switch2web2017@gmail.com";
            //string sFromPassword = "switch2web2017@#";

            //string sFrom = "logman@switch2web.com";
            //string sFromPassword = "Switch@2018#";

            string sFrom = objDB.Email;
            string sFromPassword = objDB.Password;

            string sTo = EmailID;
            string sSubject = "jobycodirect.com Signup";

            //Mail Body
            string sBody = "";
            sBody += "<b>From: </b> JobyCo Ltd. <br/>";
            sBody += "<b>Sent: </b>" + DateTime.Now.ToLongDateString() + "<br/>";
            sBody += "<b>To: </b>" + sTo + "<br/>";
            sBody += "<b>Subject: </b> jobycodirect.com Signup" + "<br/>";
            sBody += "<h1 style='background-color: navy; color: whitesmoke;padding: 0 0 0 20px;'>&nbsp;jobycodirect.com Signup</h1>";

            int iAtTheRateIndex = sTo.IndexOf("@");
            string sFirstNameFromTo = sTo.Substring(0, iAtTheRateIndex);

            sBody += "Hi " + sFirstNameFromTo + ", <br/><br/>";
            sBody += "Welcome to <b>jobycodirect.com</b>! <br/><br/>";

            sBody += "<b>Your login Id : " + EmailID + "</b><br/>";
            sBody += "<b>Your Password : " + Password + "</b><br/><br/>";

            sBody += "I hope you are finding the experience easy and helpful. ";
            sBody += "We are only a click away to help set up things and showcase the true potential of <b>jobycodirect.com</b>.<br/><br/>";
            sBody += "Please select the most suitable time via my <b>Calendar</b> for a quick conversation. ";
            sBody += "Looking forward to working with you. <br/><br/>";
            sBody += "Have a good day! <br/><br/>";

            sBody += "Kind regards, <br/>";
            sBody += "Mr. Edward Akosah, <br/>";
            sBody += "Account Executive, <br/><br/>";

            sBody += "<b><big>UK Customer Services</big></b> <br/>";
            sBody += "<a href='"+ DomainName + "'>www.jobycodirect.com</a> <br/>";
            sBody += "194 Camford Way, <br/>";
            sBody += "Luton, <br/>";
            sBody += "Bedfordshire, <br/>";
            sBody += "LU3 3AN <br/>";
            sBody += "Ph:+44 01582574569 <br/>";

            try
            {
                if (objOP.SendMail(sFrom, sTo, sSubject, sBody, sFromPassword))
                {
                    sMessage = "Signup failed";
                }
                else
                {
                    sMessage = "Signup successfull";
                }
            }
            catch { }

            return sMessage;
        }

        protected void btnSignUpForFreeAccount_Click(object sender, EventArgs e)
        {
            string sEmailID = txtEmailID.Text.Trim();
            Session["Signedup"] = sEmailID;
            Session["Login"] = sEmailID;
            Response.AppendHeader("Refresh", "3;url=/Dashboard.aspx");
            //Response.Redirect("/Dashboard.aspx");
        }
    }
}