using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

#region Required Global NameSpaces

using DataAccessLayer;
using EntityLayer;
using SecurityLayer;
using JobyCoWeb.Models;
using System.Data;

#endregion

namespace JobyCoWeb.Complaints
{
    public partial class NewComplaint : System.Web.UI.Page
    {
        #region Required Global Classes

        clsOperation objOP = new clsOperation();
        clsDB objDB = new clsDB();
        clsCryptography objCG = new clsCryptography();
        ControlModels objCM = new ControlModels();

        #endregion

        protected void Page_Load(object sender, EventArgs e)
        {
            objCM.ResetMessageBar(lblErrMsg);

            if (!IsPostBack)
            {
                #region Binding Dropdowns

                txtComplaintId.Text = objOP.GetAutoGeneratedValue("ComplaintId", "Complaints", "COMP", 9);
                objCM.FillDropDown(ddlBookingNumber, "Booking Number", "BookingId", "OrderBooking");

                DataTable dtComplaintSource = objDB.GetDropDownValues(3, 4);
                objCM.FillDropDown(ddlComplaintSource, "Complaint Source", dtComplaintSource);

                DataTable dtComplaintReason = objDB.GetDropDownValues(3, 5);
                objCM.FillDropDown(ddlComplaintReason, "Complaint Reason", dtComplaintReason);

                DataTable dtComplaintStatus = objDB.GetDropDownValues(3, 6);
                objCM.FillDropDown(ddlComplaintStatus, "Complaint Status", dtComplaintStatus);

                #endregion
            }
        }

        protected void ddlBookingNumber_SelectedIndexChanged(object sender, EventArgs e)
        {
            #region Combine Customer's Full Name

            string sCustomerId = GetCustomerIdFromBookId(ddlBookingNumber);

            string sTitle = objOP.RetrieveField2FromField1("Title", "Customers", "CustomerId", sCustomerId);
            string sFirstName = objOP.RetrieveField2FromField1("FirstName", "Customers", "CustomerId", sCustomerId);
            string sLastName = objOP.RetrieveField2FromField1("LastName", "Customers", "CustomerId", sCustomerId);

            string sCustomerName = sTitle + " " + sFirstName + " " + sLastName;
            txtCustomerName.Text = sCustomerName;

            #endregion
        }

        private string GetCustomerIdFromBookId(DropDownList ddl)
        {
            string sBookingId = ddl.SelectedItem.Text.Trim();
            string sCustomerId = string.Empty;

            if (!sBookingId.Equals("Select Booking Number"))
            {
                sCustomerId = objOP.RetrieveField2FromField1("CustomerId", "OrderBooking", "BookingId", sBookingId);
            }

            return sCustomerId;
        }
    }
}